version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
    volumes: 
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    environment: 
    - PROJECT2_DB=${PROJECT2_DB}
    deploy:
      replicas: 2
  service1:
    image: hsjhita1/service1:latest
    build: ./Service1
    ports: 
    - target: 8000
      published: 8000
    environment: 
    - PROJECT2_DB=${PROJECT2_DB}
    deploy:
      replicas: 2
  service2:
    image: hsjhita1/service2:latest
    build: ./Service2
    ports: 
    - target: 8001
      published: 8001
  service3:
    image: hsjhita1/service3:latest
    build: ./Service3
    ports: 
      - target: 8002
        published: 8002
  service4:
    image: hsjhita1/service4:latest
    build: ./Service4
    ports: 
    - target: 8003
      published: 8003
    environment: 
    - PROJECT2_DB=${PROJECT2_DB}