version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
    volumes: 
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    environment: 
    - PROJECT2_DB=${PROJECT2_DB}
  service1:
    image: 34.105.129.88:5000/service1
    build: ./Service1
    ports: 
    - target: 8000
      published: 8000
    environment: 
    - PROJECT2_DB=${PROJECT2_DB}
  service2:
    image: 34.105.129.88:5000/service2
    build: ./Service2
    ports: 
    - target: 8001
      published: 8001
  service3:
    image: 34.105.129.88:5000/service3
    build: ./Service3
    ports: 
      - target: 8002
        published: 8002
  service4:
    image: 34.105.129.88:5000/service4
    build: ./Service4
    ports: 
    - target: 8003
      published: 8003
    environment: 
    - PROJECT2_DB=${PROJECT2_DB}