---
- name: Install Docker
  hosts: all
  become: true
  roles:
  - docker

- name: Initialise Docker Swarm
  hosts: swarm-manager
  become: true
  roles:
  - docker-swarm-init

- name: Add workers to Docker Swarm
  hosts: swarm-workers
  become: true
  roles:
  - docker-swarm-workers