- name: Local Installs
  hosts: 127.0.0.1
  connection: local
  become: true
  roles:
  - docker
  - docker-swarm-init

- name: workers
  hosts: swarm-workers 
  become: true
  roles:
  - docker
  - docker-swarm-workers